version: '2'

networks:
  ros_test_bridge_network:
    driver: bridge

services:
  rosmaster:
    image: ros:noetic-robot
    command: stdbuf -o L roscore
    environment:
      - "ROS_HOSTNAME=rosmaster"
    networks:
      - ros_test_bridge_network
    restart: unless-stopped

  publisher:
    image: ros:noetic-robot
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "Hello World!" -r 2
    depends_on:
      - rosmaster
    environment:
      - "ROS_MASTER_URI=http://rosmaster:11311"
      - "ROS_HOSTNAME=publisher"
    networks:
      - ros_test_bridge_network
    restart: unless-stopped

  subscriber:
    image: ros:noetic-robot
    command: stdbuf -o L rostopic echo /chatter
    depends_on:
      - rosmaster
      - publisher
    environment:
      - "ROS_HOSTNAME=subscriber"
      - "ROS_MASTER_URI=http://rosmaster:11311"
    networks:
      - ros_test_bridge_network
    restart: unless-stopped
