version: '3.9'

services:
  rosmaster:
    image: ros:noetic-robot
    environment:
      - 'ROS_HOSTNAME=${ROS_HOSTNAME}'
    command: stdbuf -o L roscore
    network_mode: host
    #extra_hosts:
      #- "ETC_HOSTNAME_1:ETC_HOST_IP_1"
    restart: always

  talker:
    image: ros:noetic-robot
    depends_on:
      - rosmaster
    environment:
      - 'ROS_MASTER_URI=${ROS_MASTER_URI}'
      - 'ROS_HOSTNAME=${ROS_HOSTNAME}'
      #- 'ROS_IP=${ROS_IP}'
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "Hello World!" -r 2
    network_mode: host
    #extra_hosts:
      #- "ETC_HOSTNAME_1:ETC_HOST_IP_1"
    restart: always

  listener:
    image: ros:noetic-robot
    depends_on:
      - talker
    environment:
      - 'ROS_MASTER_URI=${ROS_MASTER_URI}'
      - 'ROS_HOSTNAME=${ROS_HOSTNAME}'
      #- 'ROS_IP=${ROS_IP}'
    command: stdbuf -o L rostopic echo /chatter
    network_mode: host
    #extra_hosts:
      #- "ETC_HOSTNAME_1:ETC_HOST_IP_1"
    restart: always
