version: "3.9"
services:
  rosmaster:
    image: ros:noetic-robot
    command: stdbuf -o L roscore
    environment:
      - 'ROS_HOSTNAME=${ROS_HOSTNAME}'
    network_mode: host
    #extra_hosts:
      #- "ETC_HOSTNAME_1:ETC_HOST_IP_1"
    #restart: always
    restart: unless-stopped


  publisher:
    #image: ros:noetic-robot
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
      args:
        - CATKIN_WORKSPACE_DIR=${CATKIN_WORKSPACE_DIR}
    depends_on:
      - rosmaster
    environment:
      - 'CATKIN_WORKSPACE_DIR=${CATKIN_WORKSPACE_DIR}'
      - 'ROS_MASTER_URI=${ROS_MASTER_URI}'
      - 'ROS_HOSTNAME=${ROS_HOSTNAME}'
      #- 'ROS_IP=${ROS_IP}'
    network_mode: host
    #extra_hosts:
      #- "ETC_HOSTNAME_1:ETC_HOST_IP_1"
    volumes:
      - ../src:${CATKIN_WORKSPACE_DIR}/src
    command: stdbuf -o L catkin build
    restart: unless-stopped
