version: "3.9"
services:
  peak_ltpa:
    #image: ros:noetic-robot
    build:
      context: ..
      dockerfile: docker/DockerfileCatkinBuild
      target: base
      args:
        - CATKIN_WORKSPACE_DIR=${CATKIN_WORKSPACE_DIR}
    environment:
      - 'CATKIN_WORKSPACE_DIR=${CATKIN_WORKSPACE_DIR}'
      - 'ROS_MASTER_URI=${ROS_MASTER_URI}'
      - 'ROS_HOSTNAME=${ROS_HOSTNAME}'
      #- 'ROS_IP=${ROS_IP}'
    network_mode: host
    #extra_hosts:
      #- "ETC_HOSTNAME_1:ETC_HOST_IP_1"
    #volumes:
      #- ../src:${CATKIN_WORKSPACE_DIR}/src
    #command: stdbuf -o L roslaunch peak_ltpa init.launch
    #command: stdbuf -o L roslaunch peak_ltpa init.launch
    #command: bash -c "roslaunch peak_ltpa init.launch"
    #command: sleep infinity
    #command: stdbuf -o L "source /catkin_ws/devel/setup.bash && roslaunch peak_ltpa init.launch"
    restart: unless-stopped
