version: "3.9"
services:
  ros_docker_rviz_test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
      args:
        - CATKIN_WORKSPACE_DIR=${CATKIN_WORKSPACE_DIR}
        - USERNAME=${USERNAME:-developer}
        - UID=${UID:-1000}
        - GID=${UID:-1000}
    container_name: ros_docker_rviz_test
    environment:
      - 'ROS_MASTER_URI=${ROS_MASTER_URI}'
      - 'ROS_HOSTNAME=${ROS_HOSTNAME}'
    #extra_hosts:
      #- "${ETC_HOSTNAME_1}:${ETC_HOST_IP_1}"
    image: ros_noetic_dockerfile:devel
    network_mode: host
    tty: true
    volumes:
      - ../src:/${CATKIN_WORKSPACE_DIR}/src
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "Hello World!" -r 2
    restart: always
